FROM nz-swe-sympy-22914:20261010
ENV PATH="/opt/miniconda3/envs/testbed/bin:/usr/local/bin:/usr/bin:/bin"
RUN printf '%s\n' 'export PATH=/opt/miniconda3/envs/testbed/bin:/usr/local/bin:/usr/bin:/bin' > /etc/profile.d/nz-project-python.sh
